build:
  maxIssues: 0
  weights:
    complexity: 2
    formatting: 1
    LongParameterList: 1
    comments: 1

config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: true

style:
  MaxLineLength:
    maxLineLength: 120
  MagicNumber:
    active: true
    ignoreNumbers: ["-1", "0", "1", "2"]
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: false
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: false
    ignoreNamedArgument: true
    ignoreEnums: false
    ignoreRanges: false
    ignoreLocalVariableDeclaration: false
  WildcardImport:
    active: true
    excludeImports: []

complexity:
  TooManyFunctions:
    active: true
    thresholdInFiles: 15
    thresholdInClasses: 15
    thresholdInInterfaces: 15
    thresholdInObjects: 15
    thresholdInEnums: 15
  LongParameterList:
    active: true
    functionThreshold: 6
    constructorThreshold: 7
  LongMethod:
    active: true
    threshold: 60
  ComplexMethod:
    active: true
    threshold: 15
  NestedBlockDepth:
    active: true
    threshold: 4

exceptions:
  TooGenericExceptionCaught:
    active: true
    excludes: ["**/test/**", "**/androidTest/**", "**/commonTest/**", "**/jvmTest/**", "**/jsTest/**", "**/iosTest/**"]
  SwallowedException:
    active: true
    ignoredExceptionTypes:
      - InterruptedException
      - NumberFormatException
      - ParseException
      - MalformedURLException
    allowedExceptionNameRegex: "_|(ignore|expected).*"

formatting:
  active: true
  android: false
  autoCorrect: true
  MaximumLineLength:
    active: true
    maxLineLength: 120
  TrailingComma:
    active: true
    allowTrailingComma: true
    allowTrailingCommaOnCallSite: true

naming:
  active: true
  ClassNaming:
    active: true
    classPattern: "[A-Z][a-zA-Z0-9]*"
  ConstructorParameterNaming:
    active: true
    parameterPattern: "[a-z][A-Za-z0-9]*"
    privateParameterPattern: "[a-z][A-Za-z0-9]*"
    excludeClassPattern: "$^"
  EnumNaming:
    active: true
    enumEntryPattern: "[A-Z][_a-zA-Z0-9]*"
  FunctionNaming:
    active: true
    functionPattern: "([a-z][a-zA-Z0-9]*)|(`.*`)"
  PackageNaming:
    active: true
    packagePattern: '[a-z]+(\.[a-z][A-Za-z0-9]*)*'
  TopLevelPropertyNaming:
    active: true
    constantPattern: "[A-Z][_A-Z0-9]*"
    propertyPattern: "[A-Za-z][_A-Za-z0-9]*"
    privatePropertyPattern: "_?[A-Za-z][_A-Za-z0-9]*"
